# build_and_run.ps1 — Build ScummVM (SCI engine) and launch SQ3
#
# PREREQUISITES: Visual Studio 2019/2022 with "Desktop development with C++" workload.
# Everything else (SDL2, libpng, zlib, etc.) is installed automatically via vcpkg.
#
# FIRST RUN: installs libraries + generates project + full build (~15-30 min)
# SUBSEQUENT RUNS: incremental build + launch (~1-3 min)

param(
    [string]$Config   = "Release",
    [string]$Platform = "x64",
    [switch]$NoLaunch,   # build only; skip launching the game (used for compile verification)
    [string]$Game     = "",   # launch this configured target id (e.g. "qfg1") instead of SQ3;
                              # launches by target so the existing scummvm.ini config (Roger
                              # settings, game path) is used. Empty = default SQ3 via -p path.
    [int]$SaveSlot    = -1,   # auto-load this save slot on startup (ScummVM -x / --save-slot).
                              # e.g. -SaveSlot 1 boots straight into save 001. -1 = no auto-load.
    [switch]$Regenerate       # force-regenerate scummvm.sln (e.g. after changing enabled
                              # features like the event recorder). Deletes the existing solution.
)

$ErrorActionPreference = "Stop"

$Root     = $PSScriptRoot
$DistsDir = "$Root\dists\msvc"
$GameDir  = "J:\SteamLibrary\steamapps\common\Space Quest Collection\sq3"
$RogerDir = "J:\SteamLibrary\steamapps\common\Space Quest Collection\roger"

# ── Locate MSBuild via vswhere ────────────────────────────────────────────────
$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
if (-not (Test-Path $vswhere)) {
    Write-Error "Visual Studio not found. Install VS 2019/2022 with C++ workload."
}
$MSBuild = (& $vswhere -latest -requires Microsoft.Component.MSBuild `
    -find "MSBuild\**\Bin\MSBuild.exe") | Select-Object -First 1
if (-not $MSBuild) { Write-Error "MSBuild not found." }
Write-Host "MSBuild: $MSBuild" -ForegroundColor DarkGray

# ── Locate vcpkg ──────────────────────────────────────────────────────────────
# Prefer a git-backed standalone install (so we can get a valid public baseline).
# The VS-bundled vcpkg uses an internal build hash that is not in the public
# GitHub repo, making manifest-mode baseline resolution fail.
$VSRoot   = (& $vswhere -latest -property installationPath)
$vcpkgCmd = Get-Command vcpkg -ErrorAction SilentlyContinue
$vcpkg    = @(
    "C:\vcpkg\vcpkg.exe",
    "$env:VCPKG_ROOT\vcpkg.exe",
    $(if ($vcpkgCmd) { $vcpkgCmd.Source }),
    "$VSRoot\VC\vcpkg\vcpkg.exe"
) | Where-Object { $_ -and (Test-Path $_) } | Select-Object -First 1

if (-not $vcpkg) {
    Write-Host "`nvcpkg not found. Cloning from GitHub..." -ForegroundColor Cyan
    git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
    & C:\vcpkg\bootstrap-vcpkg.bat -disableMetrics
    $vcpkg = "C:\vcpkg\vcpkg.exe"
}
Write-Host "vcpkg:   $vcpkg" -ForegroundColor DarkGray

# ── Load MSVC environment (needed by vcpkg/ninja to find cl.exe) ──────────────
# Prefer vcvarsall.bat (takes arch arg), fall back to vcvars64.bat
$vcvarsall = "$VSRoot\VC\Auxiliary\Build\vcvarsall.bat"
$vcvars64  = "$VSRoot\VC\Auxiliary\Build\vcvars64.bat"
if (Test-Path $vcvarsall) {
    $vcvarscmd = "`"$vcvarsall`" x64"
} elseif (Test-Path $vcvars64) {
    $vcvarscmd = "`"$vcvars64`""
} else {
    Write-Error "Neither vcvarsall.bat nor vcvars64.bat found under $VSRoot\VC\Auxiliary\Build - reinstall VS C++ workload"
}
Write-Host "Loading MSVC environment..." -ForegroundColor DarkGray

# Use a temp .bat file to avoid PowerShell 5.1 parsing && as a statement separator
$bat = [IO.Path]::GetTempFileName() + ".bat"
Set-Content $bat "@echo off`r`ncall $vcvarscmd >nul 2>&1`r`nset" -Encoding ascii
$envLines = cmd /c $bat
Remove-Item $bat -Force
$envLines | ForEach-Object {
    $parts = $_ -split "=", 2
    if ($parts.Length -eq 2) {
        [System.Environment]::SetEnvironmentVariable($parts[0], $parts[1], "Process")
    }
}

# ── Step 1: Install dependencies via vcpkg ────────────────────────────────────
Write-Host "`n[1/4] Installing dependencies via vcpkg (vcpkg.json)..." -ForegroundColor Cyan
Write-Host "      This takes 15-30 min on first run; cached after that." -ForegroundColor DarkGray

# Classic-mode install into the vcpkg root. The scummvm.vcxproj generated by
# create_project has no vcpkg manifest props, so it relies on the global MSBuild
# integration (`vcpkg integrate install`), which looks in <vcpkgroot>\installed\.
# Manifest mode would install into .\vcpkg_installed\ (invisible to that
# integration) and also requires a public-commit baseline, so we avoid it here.
$deps = (Get-Content "$Root\vcpkg.json" -Raw | ConvertFrom-Json).dependencies |
    ForEach-Object { "$($_):x64-windows" }

# Run from a manifest-free directory so vcpkg uses classic mode (a vcpkg.json in
# the cwd would force manifest mode, which rejects explicit package arguments).
$vcpkgDir = Split-Path $vcpkg
Push-Location $vcpkgDir
& $vcpkg install @deps --overlay-ports="$Root\.github\vcpkg-ports"
$result = $LASTEXITCODE
Pop-Location
if ($result -ne 0) { Write-Error "vcpkg install failed." }

# Integrate so MSBuild applocal-copies the runtime DLLs next to the exe.
& $vcpkg integrate install

# Point ScummVM's generated .props at the vcpkg installed tree. They reference
# $(SCUMMVM_LIBS)\include, \include\SDL2 and \lib — which is exactly the vcpkg
# x64-windows layout. Without this, <SDL.h> (in include\SDL2\) isn't found.
$env:SCUMMVM_LIBS = "$vcpkgDir\installed\x64-windows"
Write-Host "  SCUMMVM_LIBS: $env:SCUMMVM_LIBS" -ForegroundColor DarkGray

# create_project hardcodes the library names from the official ScummVM deps
# bundle. A few vcpkg packages produce a differently-named import lib, so make
# aliases the linker can find. Map: <scummvm-expected> = <vcpkg-actual>.
$libDir = "$env:SCUMMVM_LIBS\lib"
$libAliases = @{
    "zlib.lib"       = "z.lib"
    "fluidsynth.lib" = "libfluidsynth-3.lib"
}
foreach ($want in $libAliases.Keys) {
    $have = Join-Path $libDir $libAliases[$want]
    $dest = Join-Path $libDir $want
    if ((Test-Path $have) -and -not (Test-Path $dest)) {
        Copy-Item $have $dest
        Write-Host "  aliased $($libAliases[$want]) -> $want" -ForegroundColor DarkGray
    }
}
Write-Host "  Dependencies ready." -ForegroundColor Green

# ── Step 2: Build create_project.exe if needed ────────────────────────────────
$CpSln = "$Root\devtools\create_project\msvc\create_project.sln"
$CpExe = "$Root\devtools\create_project\msvc\Release\create_project.exe"

if (-not (Test-Path $CpExe)) {
    Write-Host "`n[2/4] Building create_project.exe..." -ForegroundColor Cyan
    & $MSBuild $CpSln /p:Configuration=Release /p:Platform=Win32 /m /nologo /v:minimal
    if ($LASTEXITCODE -ne 0) { Write-Error "create_project build failed." }
} else {
    Write-Host "[2/4] create_project.exe already built." -ForegroundColor DarkGray
}

# ── Step 3: Generate scummvm.sln if needed ────────────────────────────────────
$Solution = "$DistsDir\scummvm.sln"

if ($Regenerate -and (Test-Path $Solution)) {
    Write-Host "  -Regenerate: removing existing scummvm.sln to force a fresh project gen." -ForegroundColor DarkGray
    Remove-Item $Solution -Force
}

if (-not (Test-Path $Solution)) {
    Write-Host "`n[3/4] Generating scummvm.sln (SCI engine only, event recorder enabled)..." -ForegroundColor Cyan
    Push-Location $DistsDir
    # Order matters: --disable-all-engines must come BEFORE --enable-engine=sci,
    # otherwise it disables SCI again and no ENABLE_SCI define is emitted.
    # --enable-eventrecorder: ENABLE_EVENTRECORDER, so --record-mode=record/fast_playback
    # work — used by roger_spike.ps1 to drive QFG1 to the bugged town deterministically
    # (record once, replay headlessly forever) without manual play.
    & $CpExe ..\.. --msvc --disable-all-engines --enable-engine=sci --enable-eventrecorder
    $result = $LASTEXITCODE
    Pop-Location
    if ($result -ne 0) { Write-Error "Project generation failed." }
    Write-Host "  scummvm.sln generated." -ForegroundColor Green
} else {
    Write-Host "[3/4] scummvm.sln already exists." -ForegroundColor DarkGray
}

# ── Step 4: Build ScummVM ─────────────────────────────────────────────────────
Write-Host "`n[4/4] Building ScummVM ($Config|$Platform)..." -ForegroundColor Cyan
& $MSBuild $Solution /p:Configuration=$Config /p:Platform=$Platform /m /nologo /v:minimal
if ($LASTEXITCODE -ne 0) { Write-Error "ScummVM build failed." }

# ── Find the exe ──────────────────────────────────────────────────────────────
$candidates = @(
    "$DistsDir\$Config$Platform\scummvm.exe",
    "$DistsDir\$Config\$Platform\scummvm.exe",
    "$DistsDir\$Platform\$Config\scummvm.exe",
    "$DistsDir\$Config\scummvm.exe"
)
$Exe = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $Exe) {
    # Fall back to a recursive search so an unexpected layout still launches.
    $Exe = Get-ChildItem -Path $DistsDir -Recurse -Filter scummvm.exe -ErrorAction SilentlyContinue |
        Select-Object -First 1 -ExpandProperty FullName
}
if (-not $Exe) {
    Write-Error "scummvm.exe not found. Searched:`n$($candidates -join "`n")"
}

# ── Deploy ScummVM data files next to the exe ─────────────────────────────────
# create_project's MSVC project deploys the vcpkg DLLs (applocal) but NOT ScummVM's
# own data files. fonts.dat is required for TTF text (Roger hires dialogs); without
# it loadTTFFontFromArchive fails and text falls back to a tiny bitmap font. Copy
# the engine-data .dat files and the GUI theme .dat files next to the exe so they
# are on the runtime search path.
$ExeDir = Split-Path $Exe
$dataSrc = @(
    "$Root\dists\engine-data\fonts.dat",
    "$Root\gui\themes\gui-icons.dat",
    "$Root\gui\themes\translations.dat",
    "$Root\gui\themes\shaders.dat"
)
foreach ($d in $dataSrc) {
    if (Test-Path $d) {
        $dest = Join-Path $ExeDir (Split-Path $d -Leaf)
        if (-not (Test-Path $dest) -or (Get-Item $d).LastWriteTime -gt (Get-Item $dest).LastWriteTime) {
            Copy-Item $d $dest -Force
            Write-Host "  deployed $(Split-Path $d -Leaf)" -ForegroundColor DarkGray
        }
    }
}

# ── Launch SQ3 ────────────────────────────────────────────────────────────────
Write-Host "`nBuild OK  : $Exe" -ForegroundColor Green
Write-Host "Game      : $GameDir"
Write-Host "Roger art : $RogerDir"
Write-Host ""

if ($NoLaunch) {
    Write-Host "NoLaunch set - build only, skipping SQ3 launch." -ForegroundColor DarkGray
    return
}

# Build the save-slot argument shared by both launch paths.
$saveArgs = @()
if ($SaveSlot -ge 0) { $saveArgs = @("--save-slot=$SaveSlot") }

if ($Game) {
    # Launch a configured target by id (uses scummvm.ini: game path + Roger settings).
    if ($SaveSlot -ge 0) {
        Write-Host "Launching target '$Game' (auto-loading save slot $SaveSlot)..." -ForegroundColor Green
    } else {
        Write-Host "Launching target '$Game'..." -ForegroundColor Green
    }
    & $Exe @saveArgs $Game
} else {
    if (-not (Test-Path $GameDir)) { Write-Error "Game data not found at: $GameDir" }
    if ($SaveSlot -ge 0) {
        Write-Host "Launching SQ3 (auto-loading save slot $SaveSlot)..." -ForegroundColor Green
    } else {
        Write-Host "Launching SQ3..." -ForegroundColor Green
    }
    & $Exe -p $GameDir @saveArgs sq3
}
